import {ReactNode,useState} from 'react';import {NavLink,Outlet,useNavigate} from 'react-router-dom';import {Bell,BookOpen,CalendarDays,ChartNoAxesCombined,CircleHelp,ClipboardCheck,CreditCard,GraduationCap,House,Menu,Plus,Search,Settings,Users,X} from 'lucide-react';import {useApp} from './context';
export const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
export function Button({children,onClick,kind='primary',type='button'}:{children:ReactNode;onClick?:()=>void;kind?:'primary'|'ghost'|'danger';type?:'button'|'submit'}){return <button type={type} className={`btn ${kind}`} onClick={onClick}>{children}</button>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}><X/></button></div>{children}</div></div>}
export function Empty({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="empty"><div className="empty-icon"><BookOpen/></div><h3>{title}</h3><p>{text}</p>{action}</div>}
const nav=[['/','Главная',House],['/schedule','Расписание',CalendarDays],['/students','Ученики',Users],['/lessons','Занятия',BookOpen],['/homework','Домашние задания',ClipboardCheck],['/payments','Оплаты',CreditCard],['/statistics','Статистика',ChartNoAxesCombined],['/settings','Настройки',Settings],['/help','Помощь',CircleHelp]] as const;
export function Layout(){const{data,toast}=useApp();const[mobile,setMobile]=useState(false),[search,setSearch]=useState(''),[bells,setBells]=useState(false),[quick,setQuick]=useState(false);const go=useNavigate();const results=search?data.students.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())):[];return <div className="shell">
 <aside className={mobile?'sidebar open':'sidebar'}><button className="mobile-close icon" onClick={()=>setMobile(false)}><X/></button><div className="brand"><span><GraduationCap/></span><div><b>TutorDesk</b><small>Рабочее пространство репетитора</small></div></div><nav>{nav.map(([to,label,I])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setMobile(false)}><I/>{label}</NavLink>)}</nav><div className="user"><div className="avatar">МС</div><div><b>{data.profile.name}</b><small>{data.profile.subject}</small></div></div></aside>
 <main><header><button className="menu icon" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск учеников, занятий..."/>{results.length>0&&<div className="search-results">{results.map(s=><button key={s.id} onClick={()=>{go('/students/'+s.id);setSearch('')}}><div className="avatar small">{s.name[0]}</div><span><b>{s.name}</b><small>{s.grade} · {s.subject}</small></span></button>)}</div>}</div><div className="header-actions"><button className="icon notify" onClick={()=>setBells(!bells)}><Bell/><i>{data.notifications.length}</i></button><Button onClick={()=>setQuick(!quick)}><Plus/> Добавить</Button></div>{bells&&<div className="popover notifications"><b>Уведомления</b>{data.notifications.map(n=><p key={n.id}><i className={n.kind}/>{n.text}</p>)}</div>}{quick&&<div className="popover quick"><button onClick={()=>go('/students?add=1')}>Добавить ученика</button><button onClick={()=>go('/schedule?add=1')}>Добавить занятие</button><button onClick={()=>go('/payments')}>Добавить оплату</button><button onClick={()=>go('/homework')}>Добавить задание</button></div>}</header><div className="content"><Outlet/></div></main>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>} {toast&&<div className="toast">✓ {toast}</div>}</div>}
